// Generated by gencpp from file srv_pkg/SlamCmdRequest.msg
// DO NOT EDIT!


#ifndef SRV_PKG_MESSAGE_SLAMCMDREQUEST_H
#define SRV_PKG_MESSAGE_SLAMCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_pkg
{
template <class ContainerAllocator>
struct SlamCmdRequest_
{
  typedef SlamCmdRequest_<ContainerAllocator> Type;

  SlamCmdRequest_()
    : cmd(0)  {
    }
  SlamCmdRequest_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlamCmdRequest_

typedef ::srv_pkg::SlamCmdRequest_<std::allocator<void> > SlamCmdRequest;

typedef boost::shared_ptr< ::srv_pkg::SlamCmdRequest > SlamCmdRequestPtr;
typedef boost::shared_ptr< ::srv_pkg::SlamCmdRequest const> SlamCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_pkg::SlamCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_pkg::SlamCmdRequest_<ContainerAllocator1> & lhs, const ::srv_pkg::SlamCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_pkg::SlamCmdRequest_<ContainerAllocator1> & lhs, const ::srv_pkg::SlamCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26f05c6e9fb9de81f12f2b92304c2961";
  }

  static const char* value(const ::srv_pkg::SlamCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26f05c6e9fb9de81ULL;
  static const uint64_t static_value2 = 0xf12f2b92304c2961ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_pkg/SlamCmdRequest";
  }

  static const char* value(const ::srv_pkg::SlamCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 cmd\n"
;
  }

  static const char* value(const ::srv_pkg::SlamCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_pkg::SlamCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_pkg::SlamCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_PKG_MESSAGE_SLAMCMDREQUEST_H
