// Generated by gencpp from file srv_pkg/SlamCmdResponse.msg
// DO NOT EDIT!


#ifndef SRV_PKG_MESSAGE_SLAMCMDRESPONSE_H
#define SRV_PKG_MESSAGE_SLAMCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_pkg
{
template <class ContainerAllocator>
struct SlamCmdResponse_
{
  typedef SlamCmdResponse_<ContainerAllocator> Type;

  SlamCmdResponse_()
    : status(0)  {
    }
  SlamCmdResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SlamCmdResponse_

typedef ::srv_pkg::SlamCmdResponse_<std::allocator<void> > SlamCmdResponse;

typedef boost::shared_ptr< ::srv_pkg::SlamCmdResponse > SlamCmdResponsePtr;
typedef boost::shared_ptr< ::srv_pkg::SlamCmdResponse const> SlamCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_pkg::SlamCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_pkg::SlamCmdResponse_<ContainerAllocator1> & lhs, const ::srv_pkg::SlamCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_pkg::SlamCmdResponse_<ContainerAllocator1> & lhs, const ::srv_pkg::SlamCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "284aa12dd9e9e760802ac9f38036ea5e";
  }

  static const char* value(const ::srv_pkg::SlamCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x284aa12dd9e9e760ULL;
  static const uint64_t static_value2 = 0x802ac9f38036ea5eULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_pkg/SlamCmdResponse";
  }

  static const char* value(const ::srv_pkg::SlamCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"\n"
;
  }

  static const char* value(const ::srv_pkg::SlamCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_pkg::SlamCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_pkg::SlamCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_PKG_MESSAGE_SLAMCMDRESPONSE_H
