// Generated by gencpp from file srv_pkg/SlamCmd.msg
// DO NOT EDIT!


#ifndef SRV_PKG_MESSAGE_SLAMCMD_H
#define SRV_PKG_MESSAGE_SLAMCMD_H

#include <ros/service_traits.h>


#include <srv_pkg/SlamCmdRequest.h>
#include <srv_pkg/SlamCmdResponse.h>


namespace srv_pkg
{

struct SlamCmd
{

typedef SlamCmdRequest Request;
typedef SlamCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamCmd
} // namespace srv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_pkg::SlamCmd > {
  static const char* value()
  {
    return "12316eeb2759f96b72e22e8fa55290b3";
  }

  static const char* value(const ::srv_pkg::SlamCmd&) { return value(); }
};

template<>
struct DataType< ::srv_pkg::SlamCmd > {
  static const char* value()
  {
    return "srv_pkg/SlamCmd";
  }

  static const char* value(const ::srv_pkg::SlamCmd&) { return value(); }
};


// service_traits::MD5Sum< ::srv_pkg::SlamCmdRequest> should match
// service_traits::MD5Sum< ::srv_pkg::SlamCmd >
template<>
struct MD5Sum< ::srv_pkg::SlamCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_pkg::SlamCmd >::value();
  }
  static const char* value(const ::srv_pkg::SlamCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_pkg::SlamCmdRequest> should match
// service_traits::DataType< ::srv_pkg::SlamCmd >
template<>
struct DataType< ::srv_pkg::SlamCmdRequest>
{
  static const char* value()
  {
    return DataType< ::srv_pkg::SlamCmd >::value();
  }
  static const char* value(const ::srv_pkg::SlamCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_pkg::SlamCmdResponse> should match
// service_traits::MD5Sum< ::srv_pkg::SlamCmd >
template<>
struct MD5Sum< ::srv_pkg::SlamCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_pkg::SlamCmd >::value();
  }
  static const char* value(const ::srv_pkg::SlamCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_pkg::SlamCmdResponse> should match
// service_traits::DataType< ::srv_pkg::SlamCmd >
template<>
struct DataType< ::srv_pkg::SlamCmdResponse>
{
  static const char* value()
  {
    return DataType< ::srv_pkg::SlamCmd >::value();
  }
  static const char* value(const ::srv_pkg::SlamCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_PKG_MESSAGE_SLAMCMD_H
